### ISSUE TITLE
Zoom Option for full screen viewing

### ISSUE THREAD

**Issue by JahinAbrar** [jmir1/aniyomi#126]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to the **[latest version](https://github.com/jmir1/aniyomi/releases)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

When we watch animes on phone it is not full screened in the original size, so usually apps provide a zoom to fill or resize option which helps to make the video fullscreen in phone with notch...

I am currently watching One Piece in aniyomi, as the video shape of one piece is square i am having problems, so it would be really nice if aniyomi had resize/zoom to fill option.

**Comment by Aeshter** [comment]
If you are watching anime in dub, then the idea is excellent! But if it is on sub, then if the video is zoomed-in, it will be harder to read the subtitles “if you can’t understand Japanese” since the subtitles are hardcoded. Unless a service supports soft subtitles that are not burned in the video but just an overlay, the subtitles will adjust their location even if you zoom in on the video.

P.S. I might be wrong, but this is my idea. Please correct me if I am wrong.

**Comment by jmir1** [comment]
Closing because this feature was added
