### ISSUE TITLE
Animepahe extension is not working, (error in getting links).

### ISSUE THREAD

**Issue by ScottAXS** [jmir1/aniyomi#166]

**Comment by mnabid** [comment]
*I'm pretty sure the correct place to post this issue would be [jmir1/aniyomi-extensions](https://github.com/jmir1/aniyomi-extensions).*

This happens because kwik added Cloudflare captcha to prevent scraping their links. I doubt **@**‎**jmir1** can do anything to bypass it. **The only workaround is to solve the captcha yourself.**

1. Open the anime in WebView.
2. Click any episode, then click "Download" (you might get an ad, if yes then go back).
3. Select any quality to "download" (doesn't matter, 'cause we're not downloading anything).
4. You'll get another ad. Wait 5 seconds then click "Skip ad".
5. NOW you would get a captcha (finally!). Solve the captcha, submit it.
6. Now go back to Aniyomi and profit.

**Comment by jmir1** [comment]
Thanks for summarizing the fix. And yes, this is the wrong place for this issue

**Comment by jmir1** [comment]
Thanks for summarizing the fix. And yes, this is the wrong place for this issue

**Comment by sek1111** [comment]
For some reason animepahe doesn't provide me with captcha, After trying this method yesterday it worked but after I sleep error getting links again but this time when i try the method it directly leads me to the download page without the captcha.
