### ISSUE TITLE
App crashing when resume button is clicked 

### ISSUE THREAD

**Issue by H3LLB0Y101** [jmir1/aniyomi#256]
### Steps to reproduce

1. open aniyomi
2. open manga category
3. click on manga
4. click resume button
5. app crashes

### Expected behavior

When the resume button is clicked, it should open the manga from the page of the chapter where i was last reading.

### Actual behavior

The app crashes and a pop up shows 
"Aniyomi has stopped"
Close×

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/jmir1/aniyomi/files/7611798/tachiyomi_crash_logs.txt)

### Aniyomi version

0.12.3.5

### Android version

8.0.0

### Device

Samsung Galaxy J5 Prime SM-G570M

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
it seems to be caused by the app trying to change the screen rotation...
![27-11-2021-150036](https://user-images.githubusercontent.com/43830312/143684661-d209ac1f-5052-4c86-aba6-e61fc09e8c1f.png)
can you tell me your reader settings?
also, does it only happen when clicking the "resume" button and not when clicking the chapter directly?

**Comment by H3LLB0Y101** [comment]
![Screenshot_20211127-135024_Aniyomi](https://user-images.githubusercontent.com/88006243/143691614-af2efc51-22df-48c7-9790-1ab0e61533a0.jpg)
![Screenshot_20211127-135033_Aniyomi](https://user-images.githubusercontent.com/88006243/143691615-4a784be0-70ab-4062-8183-076db2ba6564.jpg)
![Screenshot_20211127-135040_Aniyomi](https://user-images.githubusercontent.com/88006243/143691616-0dd75121-8d8b-4769-a03f-514e6616529a.jpg)
These are my reader settings.
Also this only happens when i click the resume button.
It works fine when i click the chapter directly.
@jmir1

**Comment by nirjon001** [comment]
When I start reading manga ...... 
App suddenly crashes......

--------- beginning of crash
03-29 22:28:24.274 16163 16163 E AndroidRuntime: FATAL EXCEPTION: main
03-29 22:28:24.274 16163 16163 E AndroidRuntime: Process: xyz.jmir.tachiyomi.mi.debug, PID: 16163
03-29 22:28:24.274 16163 16163 E AndroidRuntime: android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{147aed7 u0 xyz.jmir.tachiyomi.mi.debug/eu.kanade.tachiyomi.extension.util.AnimeExtensionInstallService}
03-29 22:28:24.274 16163 16163 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2005)
03-29 22:28:24.274 16163 16163 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
03-29 22:28:24.274 16163 16163 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:232)
03-29 22:28:24.274 16163 16163 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7441)
03-29 22:28:24.274 16163 16163 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-29 22:28:24.274 16163 16163 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
03-29 22:28:24.274 16163 16163 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
--------- beginning of system
--------- beginning of main
04-04 11:19:12.057 28405 28405 E hiyomi.mi.debu: Not starting debugger since process cannot load the jdwp agent.
04-04 11:19:16.360 28405 28498 E ion     : ioctl c0044901 failed with code -1: Invalid argument
04-04 11:19:16.984 28405 28821 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-04 11:19:16.984 28405 28518 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-04 11:19:16.985 28405 28823 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-04 11:19:16.985 28405 28517 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-04 11:19:16.985 28405 28828 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-04 11:19:16.985 28405 28830 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-04 11:19:16.985 28405 28827 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-04 11:19:16.985 28405 28829 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-04 11:19:16.985 28405 28516 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-04 11:19:17.904 28405 28826 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-04 11:19:17.921 28405 28822 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-04 11:19:17.932 28405 28822 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-04 11:19:17.939 28405 28826 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-04 11:19:18.442 28405 28517 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-04 11:19:18.443 28405 28824 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-04 11:19:18.447 28405 28826 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-04 11:19:18.451 28405 28822 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-04 11:19:18.699 28405 28822 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-04 11:19:20.237 28405 28498 E BufferQueueProducer: [unnamed-28405-0](this:0x83724000,id:0,api:1,p:28405,c:28405) setMaxDequeuedBufferCount: 2 dequeued buffers would exceed the maxBufferCount (2) (maxAcquired 1 async 0 mDequeuedBufferCannotBlock 0)
04-04 11:19:20.237 28405 28498 E Surface : IGraphicBufferProducer::setBufferCount(3) returned Invalid argument
04-04 11:19:20.239 28405 28498 E ion     : ioctl c0044901 failed with code -1: Invalid argument
04-04 11:19:57.500 29360 29360 E hiyomi.mi.debu: Not starting debugger since process cannot load the jdwp agent.
04-04 11:20:01.403 29360 29424 E ion     : ioctl c0044901 failed with code -1: Invalid argument
04-04 11:20:01.488 29360 29589 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-04 11:20:01.488 29360 29588 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-04 11:20:01.618 29360 29588 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-04 11:20:12.215 29360 29833 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-04 11:20:12.216 29360 29831 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-04 11:20:12.217 29360 29832 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-04 11:20:12.993 29360 29872 E chromium: [ERROR:simple_index_file_posix.cc(36)] opendir /data/user/0/xyz.jmir.tachiyomi.mi.debug/cache/WebView/Default/HTTP Cache/Code Cache/js: No such file or directory (2)
04-04 11:20:12.993 29360 29875 E chromium: [ERROR:simple_index_file_posix.cc(36)] opendir /data/user/0/xyz.jmir.tachiyomi.mi.debug/cache/WebView/Default/HTTP Cache/Code Cache/wasm: No such file or directory (2)
04-04 11:20:12.993 29360 29872 E chromium: [ERROR:simple_index_file.cc(575)] Could not reconstruct index from disk
04-04 11:20:12.993 29360 29875 E chromium: [ERROR:simple_index_file.cc(575)] Could not reconstruct index from disk
04-04 11:20:13.035 29360 29837 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-04 11:20:13.043 29360 29828 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-04 11:20:13.051 29360 29837 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-04 11:20:13.058 29360 29837 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-04 11:20:13.218 29360 29590 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-04 11:20:13.220 29360 29836 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-04 11:20:13.222 29360 29828 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-04 11:20:13.226 29360 29837 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-04 11:20:13.233 29360 29827 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
App version: 0.12.3.6-4513 (standard, 98b7e1dbe, 72, 2022-04-01T17:57Z)
Android version: 10 (SDK 29)
Android build ID: QP1A.190711.020 release-keys
Device brand: Symphony
Device manufacturer: Symphony
Device name: Z16
Device model: Z16
Device product name: Z16
