### ISSUE TITLE
The app suddenly exits when I open it

### ISSUE THREAD

**Issue by Slecchi** [jmir1/aniyomi#53]
Okay, so I was just doing some other stuff on my phone like YouTube and Discord. I decided I wanted to continue watching a certain anime but whenever I open the app it suddenly crashes/exits out. I have no why this is suddenly happening

**Comment by EmanDev** [comment]
Happened to me also. For me, the steps to reproduce are:
1. Disconnect from the internet 
2. Open the app
3. Watch anime
4. "download" an episode 
5. Since you can't download while disconnected from the internet, you connect now and the app will crash,

had to reinstall to use it again, for now I switched to version 0.11.1.4-mi-3670
